const C=window.GK_CONFIG||{};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let state={articles:[],facts:[],questions:[],categories:[],site:{}};let selectedQuiz=null;let currentFilter='All';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const catIcon={India:'🇮🇳',World:'🌐',Economy:'📊','Science & Tech':'🧪',Science:'🧪',Technology:'💻',Environment:'🌱',Sports:'🏆','Awards & Honours':'🏅',Awards:'🏅',Appointments:'👤',Defence:'🛡️','Static GK':'📚',Exams:'🎓'};
function fmtDate(d){try{return new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}catch(e){return ''}}
async function api(action,params={}){if(!C.API_URL)return demo(action,params);const u=new URL(C.API_URL);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u.toString());if(!r.ok)throw new Error('API request failed');return r.json()}
function demo(action,params={}){const now=new Date().toISOString();const arts=[
{id:'isro',title:'ISRO launches Aditya-L1 mission towards the Sun',category:'Science & Tech',summary:"India’s first space-based observatory to study the Sun has been successfully launched, marking a major step in space research.",whyImportant:'The mission helps scientists study solar activity and space weather from the L1 point, making it important for science and technology current affairs.',keyFacts:['Organisation: ISRO','Mission Name: Aditya-L1','Launch Site: Sriharikota','Destination: L1 Lagrange Point','Objective: Study the Sun and solar activities'],eventDate:now,image:'https://images.unsplash.com/photo-1517976547714-720226b864c1?auto=format&fit=crop&w=1600&q=85',verified:true,confidence:98,sources:[{name:'ISRO Official Website',url:'https://www.isro.gov.in/'},{name:'PIB Press Release',url:'https://pib.gov.in/'}]},
{id:'indiaeconomy',title:'India becomes the 4th largest economy in the world',category:'Economy',summary:'A major economic ranking update is converted into a concise exam-ready fact.',whyImportant:'Economic rankings are frequently asked in current-affairs and competitive examinations.',keyFacts:['Global economic ranking','India','Official statistics should be verified'],eventDate:now,image:'https://images.unsplash.com/photo-1524498250077-390f9e378fc0?auto=format&fit=crop&w=900&q=80',verified:true,confidence:96,sources:[{name:'Official Economic Source',url:'https://www.imf.org/'}]},
{id:'g20',title:'India to host G20 Education Working Group meet',category:'India',summary:'Important government and diplomacy updates appear as short, verified knowledge cards.',whyImportant:'G20-related meetings matter for diplomacy, education policy and international affairs.',keyFacts:['Host: India','Forum: G20','Topic: Education'],eventDate:now,image:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=900&q=80',verified:true,confidence:95,sources:[{name:'G20 Official',url:'https://www.g20.org/'}]},
{id:'rain',title:'IMD warns of heavy rainfall in several states',category:'Environment',summary:'Official weather and disaster-related alerts can be summarized when they have national relevance.',whyImportant:'Official alerts may matter for geography, climate and disaster-management awareness.',keyFacts:['Agency: IMD','Topic: Heavy Rainfall'],eventDate:now,image:'https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=900&q=80',verified:true,confidence:95,sources:[{name:'IMD',url:'https://mausam.imd.gov.in/'}]},
{id:'parliament',title:'New Parliament building gets Green Building certification',category:'India',summary:'Government infrastructure milestones are summarized into useful GK points.',whyImportant:'National institutions and infrastructure are common static and current GK themes.',keyFacts:['Country: India','Topic: Parliament','Theme: Green certification'],eventDate:now,image:'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=900&q=80',verified:true,confidence:96,sources:[{name:'PIB',url:'https://pib.gov.in/'}]},
{id:'renewable',title:"India’s renewable energy capacity crosses 200 GW",category:'Environment',summary:'A concise update on clean-energy capacity and sustainability.',whyImportant:'Renewable-energy milestones are relevant to environment, economy and energy policy.',keyFacts:['Renewable energy','Capacity milestone','India'],eventDate:now,image:'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=900&q=80',verified:true,confidence:97,sources:[{name:'MNRE',url:'https://mnre.gov.in/'}]},
{id:'rbi',title:'RBI keeps repo rate unchanged at 6.50%',category:'Economy',summary:'Monetary policy decisions are converted into simple, exam-focused notes.',whyImportant:'Repo rate and RBI policy decisions are frequently tested in banking and economy exams.',keyFacts:['Institution: RBI','Policy tool: Repo rate','Decision: Unchanged'],eventDate:now,image:'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=900&q=80',verified:true,confidence:97,sources:[{name:'Reserve Bank of India',url:'https://www.rbi.org.in/'}]},
{id:'sports',title:'India wins 12 medals at Asian Games 2025',category:'Sports',summary:'Tournament results can be published with winners, venues, medals and records.',whyImportant:'Sports records and winners are common current-affairs questions.',keyFacts:['Country: India','Event: Asian Games','Medal tally update'],eventDate:now,image:'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=900&q=80',verified:true,confidence:94,sources:[{name:'Official Sports Federation',url:'https://olympics.com/'}]}
];
const data={bootstrap:{articles:arts,facts:[],questions:[{question:'Which organization launched the Aditya-L1 mission?',options:['NASA','ISRO','ESA','JAXA'],answer:1,explanation:'Aditya-L1 is an Indian solar mission launched by ISRO.',category:'Science & Tech'}],categories:['India','World','Economy','Science & Tech','Environment','Sports','Awards & Honours','Appointments','Defence','Static GK'],site:{name:'GK Guide',tagline:'Learn Today. Stay Ahead.',quote:'Education is the most powerful weapon which you can use to change the world.',quoteAuthor:'Nelson Mandela'}}};
if(action==='ask')return Promise.resolve({ok:true,answer:'Demo mode: connect the Apps Script API to answer from your published GK database and configured AI model.',sources:[]});return Promise.resolve(data[action]||{});
}
async function load(){try{const d=await api('bootstrap');state={...state,...d};render()}catch(e){console.error(e);$('#latestGrid').innerHTML='<div class="empty">Could not load the knowledge feed. Check API configuration.</div>'}}
function render(){const a=state.articles||[];const site=state.site||{};$('#siteName').textContent=site.name||'GK Guide';$('#footerName').textContent=site.name||'GK Guide';$('#siteTagline').textContent=site.tagline||'Learn Today. Stay Ahead.';$('#quoteText').textContent='“'+(site.quote||'Education is the most powerful weapon which you can use to change the world.')+'”';$('#quoteAuthor').textContent='— '+(site.quoteAuthor||'Nelson Mandela');if(C.ADMIN_URL){$('#adminLink').href=C.ADMIN_URL}else{$('#adminLink').style.display='none'};renderNav();renderHero(a);renderFilters();renderArticles(a.slice(4));renderCategories();renderQuiz((state.questions||[])[0]);renderTrending(a)}
function renderNav(){const base=['Home',...(state.categories||[]).slice(0,9),'More'];$('#categoryNav').innerHTML=base.map((c,i)=>`<a href="#" class="nav-item ${i===0?'active':''}" data-nav="${esc(c)}"><span>${c==='Home'?'⌂':(catIcon[c]||'•')}</span>${esc(c)}</a>`).join('');$$('[data-nav]').forEach(x=>x.onclick=e=>{e.preventDefault();const c=x.dataset.nav;if(c==='Home'||c==='More')return;applyFilter(c)})}
function renderHero(a){const hero=a[0];if(hero)$('#heroStory').innerHTML=`<img src="${esc(hero.image||C.FALLBACK_IMAGE)}" alt=""><div class="lead-gradient"></div><div class="lead-copy"><span class="top-story">TOP STORY</span><h1>${esc(hero.title)}</h1><p>${esc(hero.summary)}</p><div class="meta-row"><span>▣ ${fmtDate(hero.eventDate)}</span><span>◆ ${esc(hero.category)}</span><span class="verified-dot">Verified</span></div><span class="read-btn">Read Full Story →</span></div>`;$('#heroStory').onclick=()=>openArticle(hero);$('#heroStack').innerHTML=a.slice(1,4).map(x=>`<article class="mini-story" data-id="${esc(x.id)}"><img src="${esc(x.image||C.FALLBACK_IMAGE)}"><div class="mini-story-copy"><h3>${esc(x.title)}</h3><div class="mini-meta"><span>${esc(x.category)}</span><span>•</span><span>${fmtDate(x.eventDate)}</span></div></div></article>`).join('');$$('.mini-story').forEach(el=>el.onclick=()=>openArticle(a.find(x=>String(x.id)===el.dataset.id)))}
function renderTrending(a){const tags=[...new Set(a.map(x=>x.category).filter(Boolean)),'UPSC','Artificial Intelligence'].slice(0,9);$('#trendingTopics').innerHTML=tags.map(t=>`<span class="trend-chip">${esc(t)}</span>`).join('')}
function renderFilters(){const cats=['All',...(state.categories||[]).slice(0,7)];$('#filterRow').innerHTML=cats.map(c=>`<button class="filter-btn ${c===currentFilter?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>applyFilter(b.dataset.filter))}
function applyFilter(c){currentFilter=c;renderFilters();const list=c==='All'?state.articles.slice(4):state.articles.filter(x=>x.category===c);renderArticles(list);$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===c))}
function renderArticles(list){$('#latestGrid').innerHTML=list.length?list.slice(0,12).map(x=>`<article class="update-card" data-article="${esc(x.id)}"><div class="update-image"><img src="${esc(x.image||C.FALLBACK_IMAGE)}" loading="lazy"><span class="category-pill">${esc(x.category)}</span></div><div class="update-body"><h3>${esc(x.title)}</h3><div class="card-meta"><span>${fmtDate(x.eventDate)}</span><span>${x.verified?'● Verified':'Review'}</span></div></div></article>`).join(''):'<div class="empty">No matching updates.</div>';$$('[data-article]').forEach(el=>el.onclick=()=>openArticle(state.articles.find(x=>String(x.id)===el.dataset.article)))}
function renderCategories(){const counts={};(state.articles||[]).forEach(x=>counts[x.category]=(counts[x.category]||0)+1);$('#categoryCards').innerHTML=(state.categories||[]).slice(0,10).map(c=>`<article class="browse-card" data-cat="${esc(c)}"><span class="browse-icon">${catIcon[c]||'📘'}</span><span><b>${esc(c)}</b><small>${counts[c]||0}+ articles</small></span></article>`).join('');$$('[data-cat]').forEach(x=>x.onclick=()=>applyFilter(x.dataset.cat))}
function renderQuiz(q){if(!q){$('#quizArea').innerHTML='<p>No quiz published yet.</p>';return}selectedQuiz=null;$('#quizArea').innerHTML=`<p>${esc(q.question)}</p>${q.options.map((o,i)=>`<button class="quiz-option" data-option="${i}"><span class="quiz-radio"></span><span>${esc(o)}</span></button>`).join('')}<div class="quiz-actions"><button class="primary-btn" id="submitQuiz">Submit Answer</button><button class="text-btn" id="showExplanation">View Explanation →</button></div><div class="quiz-result" id="quizResult"></div>`;$$('[data-option]').forEach(b=>b.onclick=()=>{selectedQuiz=Number(b.dataset.option);$$('[data-option]').forEach(x=>x.classList.toggle('selected',x===b))});$('#submitQuiz').onclick=()=>{$('#quizResult').textContent=selectedQuiz===Number(q.answer)?'✓ Correct! '+q.explanation:'Not quite. '+q.explanation};$('#showExplanation').onclick=()=>$('#quizResult').textContent=q.explanation||''}
function openArticle(x){if(!x)return;sessionStorage.setItem('gk_article',JSON.stringify(x));location.href='article.html?id='+encodeURIComponent(x.id)}
async function ask(q,target){q=(q||'').trim();if(!q)return;target.classList.add('show');target.textContent='Thinking…';try{const r=await api('ask',{q});target.textContent=r.answer||r.error||'No answer available.'}catch(e){target.textContent='Could not answer right now.'}}
$('#searchBtn').onclick=()=>{const q=$('#searchInput').value.trim().toLowerCase();currentFilter='Search';renderArticles(state.articles.filter(x=>(x.title+' '+x.summary+' '+x.category).toLowerCase().includes(q)))};$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click()});$('#viewAll').onclick=()=>{currentFilter='All';renderFilters();renderArticles(state.articles)};$('#askBtn').onclick=()=>ask($('#askInput').value,$('#askAnswer'));$('#themeToggle').onclick=()=>document.body.classList.toggle('dark');
function openAsk(){const m=$('#askModal'),b=$('#modalBackdrop');m.classList.add('open');b.classList.add('open');m.setAttribute('aria-hidden','false')}function closeAsk(){$('#askModal').classList.remove('open');$('#modalBackdrop').classList.remove('open');$('#askModal').setAttribute('aria-hidden','true')}$('#askTop').onclick=openAsk;$('#modalClose').onclick=closeAsk;$('#modalBackdrop').onclick=closeAsk;$('#modalAskBtn').onclick=()=>ask($('#modalAskInput').value,$('#modalAskAnswer'));
load();
